export const ERROR_CODES = {
  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Auth
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED: 'PASSWORD_RESET_TOKEN_EXPIRED',

  // Domain
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  CANNOT_REMOVE_LAST_SUPER_ADMIN: 'CANNOT_REMOVE_LAST_SUPER_ADMIN',
  CANNOT_ASSIGN_SUPER_ADMIN: 'CANNOT_ASSIGN_SUPER_ADMIN',

  // Agents
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_CODE_EXISTS: 'AGENT_CODE_EXISTS',
  AGENT_VERSION_IMMUTABLE: 'AGENT_VERSION_IMMUTABLE',
  AGENT_DRAFT_VERSION_EXISTS: 'AGENT_DRAFT_VERSION_EXISTS',
  AGENT_NO_DRAFT_TO_PUBLISH: 'AGENT_NO_DRAFT_TO_PUBLISH',
  AGENT_INVALID_STATE: 'AGENT_INVALID_STATE',

  // Workflows
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_CODE_EXISTS: 'WORKFLOW_CODE_EXISTS',
  WORKFLOW_VERSION_IMMUTABLE: 'WORKFLOW_VERSION_IMMUTABLE',
  WORKFLOW_DRAFT_VERSION_EXISTS: 'WORKFLOW_DRAFT_VERSION_EXISTS',
  WORKFLOW_NO_DRAFT_TO_PUBLISH: 'WORKFLOW_NO_DRAFT_TO_PUBLISH',
  WORKFLOW_INVALID_STATE: 'WORKFLOW_INVALID_STATE',
  WORKFLOW_INVALID_AGENT_REF: 'WORKFLOW_INVALID_AGENT_REF',
  WORKFLOW_INVALID_GRAPH: 'WORKFLOW_INVALID_GRAPH',

  // Prompts
  PROMPT_NOT_FOUND: 'PROMPT_NOT_FOUND',
  PROMPT_CODE_EXISTS: 'PROMPT_CODE_EXISTS',
  PROMPT_VERSION_IMMUTABLE: 'PROMPT_VERSION_IMMUTABLE',
  PROMPT_DRAFT_VERSION_EXISTS: 'PROMPT_DRAFT_VERSION_EXISTS',
  PROMPT_NO_DRAFT_TO_PUBLISH: 'PROMPT_NO_DRAFT_TO_PUBLISH',
  PROMPT_EMPTY_CONTENT: 'PROMPT_EMPTY_CONTENT',
  PROMPT_INVALID_STATE: 'PROMPT_INVALID_STATE',
  PROMPT_NOT_ASSIGNABLE: 'PROMPT_NOT_ASSIGNABLE',

  // Tools
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_CODE_EXISTS: 'TOOL_CODE_EXISTS',
  TOOL_VERSION_IMMUTABLE: 'TOOL_VERSION_IMMUTABLE',
  TOOL_DRAFT_VERSION_EXISTS: 'TOOL_DRAFT_VERSION_EXISTS',
  TOOL_NO_DRAFT_TO_PUBLISH: 'TOOL_NO_DRAFT_TO_PUBLISH',
  TOOL_INVALID_STATE: 'TOOL_INVALID_STATE',
  TOOL_TYPE_IMMUTABLE: 'TOOL_TYPE_IMMUTABLE',
  TOOL_SECRET_IN_CONFIG: 'TOOL_SECRET_IN_CONFIG',
  TOOL_NOT_ASSIGNABLE: 'TOOL_NOT_ASSIGNABLE',
  TOOL_REFS_INVALID: 'TOOL_REFS_INVALID',

  // Executions
  EXECUTION_NOT_FOUND: 'EXECUTION_NOT_FOUND',
  EXECUTION_NOT_STARTABLE: 'EXECUTION_NOT_STARTABLE',
  EXECUTION_NOT_CANCELLABLE: 'EXECUTION_NOT_CANCELLABLE',
  EXECUTION_NOT_RETRYABLE: 'EXECUTION_NOT_RETRYABLE',
  EXECUTION_INVALID_DEFINITION: 'EXECUTION_INVALID_DEFINITION',
  EXECUTION_AGENT_UNAVAILABLE: 'EXECUTION_AGENT_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
